backend:
  name: git-gateway

local_backend: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Галереи"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Название альбома"
        name: "title"
        widget: "string"
      - label: "Описание"
        name: "description"
        widget: "text"
        required: false
      - label: "Дата съемки"
        name: "date"
        widget: "datetime"
      - label: "Фотографии"
        name: "images"
        widget: "list"
        fields:
          - label: "Фото"
            name: "image"
            widget: "image"
